name: Metrics
on:
  # Schedule updates (each 15 days)
  schedule: [{cron: "0 5 */15 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          filename: pdf-bot.metrics.svg
          template: repository
          user: MrBotDeveloper
          repo: PDF-Bot
          plugin_lines: yes 
          plugin_followup: yes
